object Versions {
    const val kotlin = "1.3.50"
    const val supportLibrary = "28.0.0"
    const val multidex = "1.0.3"
    const val expressoCore = "2.2.2"
    const val jUnit = "4.12"
    const val butterKnife = "8.4.0"
    const val leakCanary = "1.5"
    const val crashlytics = "2.6.5"
    const val timber = "4.7.1"
    const val retrofit = "2.1.0"
    const val okhttp = "3.4.1"
    const val gson = "2.7"
    const val dagger = "2.7"
    const val picasso = "2.5.2"
    const val circleImageView = "2.1.0"
    const val javaxAnnotation = "1.0"
    const val calligraphy = "2.2.0"
    const val markdownView = "1.0.3"
}

object Libs {
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    const val supportAppcompatV7 = "com.android.support:appcompat-v7:${Versions.supportLibrary}"
    const val supportAppcompatV4 = "com.android.support:support-v4:${Versions.supportLibrary}"
    const val supportRecyclerView = "com.android.support:recyclerview-v7:${Versions.supportLibrary}"
    const val supportCardView = "com.android.support:cardview-v7:${Versions.supportLibrary}"
    const val supportDesign = "com.android.support:design:${Versions.supportLibrary}"
    const val multidex = "com.android.support:multidex:${Versions.multidex}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val butterknife = "com.jakewharton:butterknife:${Versions.butterKnife}"
    const val butterknifeCompiler = "com.jakewharton:butterknife-compiler:${Versions.butterKnife}"
    const val leakCannary = "com.squareup.leakcanary:leakcanary-android:${Versions.leakCanary}"
    const val leakCannaryNoOp = "com.squareup.leakcanary:leakcanary-android-no-op:${Versions.leakCanary}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitRxJava = "com.squareup.retrofit2:adapter-rxjava:${Versions.retrofit}"
    const val okhttpLoggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val retrofitGson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    const val javaxAnnotation = "javax.annotation:jsr250-api:${Versions.javaxAnnotation}"
    const val markdownView = "com.github.mukeshsolanki:MarkdownView-Android:${Versions.markdownView}"
    const val crashlytics = "com.crashlytics.sdk.android:crashlytics:${Versions.crashlytics}@aar"
    const val calligraphy = "uk.co.chrisjenx:calligraphy:${Versions.calligraphy}"
    const val circleImageView = "de.hdodenhof:circleimageview:${Versions.circleImageView}"
    const val picasso = "com.squareup.picasso:picasso:${Versions.picasso}"
}
